.\"
.\" nij - a nodeinfo.json manager/editor
.\" Copyright (c) 2015 Charles Lehner
.\"
.\" Usage of the works is permitted provided that this instrument is
.\" retained with the works, so that any entity that uses the works is
.\" notified of this instrument.
.\"
.\"DISCLAIMER: THE WORKS ARE WITHOUT WARRANTY.
.\"
.Dd 2015-09-10
.Dt NIJ 1
.Os
.Sh NAME
.Nm nij
.Nd Manage and edit nodeinfo.json files
.Sh SYNOPSIS
.Nm nij ls
.Nm nij Op Fl r Ar name
.Ic init
.Nm nij Op Fl r Ar name
.Ic add Ar path
.Nm nij Op Fl r Ar name
.Ic rm
.Nm nij Op Fl r Ar name
.Ic check
.Nm nij Op Fl r Ar name
.Ic touch
.Nm nij Op Fl r Ar name
.Ic get Op Ar property
.Nm nij Op Fl r Ar name
.Ic set Op Ar property Op Ar value
.Nm nij Op Fl r Ar name
.Ic edit Op Ar property
.Sh DESCRIPTION
.Nm
is a command-line program for managing nodeinfo.json files.
.Sh AUTHOR
.Nm
was written by
.An Charles Lehner Aq Mt cel@h.celehner.com .
