.\"
.\" nij - a nodeinfo.json manager/editor
.\" Copyright (c) 2015 Charles Lehner
.\"
.\" Usage of the works is permitted provided that this instrument is
.\" retained with the works, so that any entity that uses the works is
.\" notified of this instrument.
.\"
.\"DISCLAIMER: THE WORKS ARE WITHOUT WARRANTY.
.\"
.Dd 2015-09-10
.Dt NIJ 1
.Os
.Sh NAME
.Nm nij
.Nd Manage and edit nodeinfo.json files
.Sh SYNOPSIS
.Nm nij ls
.Nm nij Ic add Ar name Ar path
.Nm nij Ic rm Ar name ...
.Nm nij Ic check Op Ar name ...
.Nm nij Ic init Op Ar name
.Nm nij Ic touch Op Ar name ...
.Nm nij Ic cat Op Ar name ...
.Nm nij Ic put Ar name
.Nm nij Ic edit Op Ar name ...
.Sh DESCRIPTION
.Nm
is a command-line program for managing nodeinfo.json files.
.Sh COMMANDS
.Bl -tag -width Ds
.It Ic ls
List remotes, which are mappings of names to path names of nodeinfo.json files.
.It Ic add Ar name Ar path
Add a nodeinfo.json file to the remotes list.
.Ar path
may be a pathname or a URL of the form
scp://host/path
.It Ic rm Ar name ...
Remove the given nodeinfo.json files from the remotes list.
.It Ic check Op Ar name ...
Validate the given nodeinfo.json files. If no arguments are given, validate
all the files in the remotes list.
.It Ic init Op Ar name
Interactively create or update a nodeinfo.json file. If the file does not yet
exist, some values will be populated with guessed data.
.It Ic touch Op Ar name ...
Update the last modified date of the given nodeinfo.json files.
.It Ic cat Op Ar name ...
Get the contents of the given nodeinfo.json files.
.It Ic put Ar name
Write stdin to the given nodeinfo.json file, if it is valid JSON.
.It Ic edit Op Ar name ...
Edit the given nodeinfo.json files using your
.Ev EDITOR or
.Xr vi 1 . After editing, if a file is not valid JSON, the user is prompted
to re-edit it. Before saving, the last_modified property is set to the current
time.
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa ~/.config/nij.json
This file stores
.Nm
\(aqs remotes list, in JSON format. It may be updated by the commands
.Ic add ,
.Ic init ,
and
.Ic rm .
.El
.Sh EXAMPLES
Add a remote:
.Dl nij add foo scp://me@example.org//var/www/nodeinfo.json
.Pp
Interactively set up the nodeinfo.json file for remote
.Ar foo :
.Dl nij init foo
.Pp
Edit the nodeinfo.json file using
.Ev EDITOR :
.Dl nij edit foo
.Sh AUTHOR
.Nm
was written by
.An Charles Lehner Aq Mt cel@h.celehner.com .
